### PR TITLE
Connect-api

### PR DESCRIPTION
**Pull request by jellywiz**
### Project requirements

In the previous project you developed the *add book* and *remove book* features directly in your application using Redux and React state. Now you should refactor your code to use the *Bookstore API* to add and remove books.

- Read the [Bookstore API documentation](https://www.notion.so/Bookstore-API-51ea269061f849118c65c0a53e88a739) to learn how to use the API.
- Use [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) or [`axios`](https://axios-http.com/docs/intro) with [`createAsyncThunk`](https://redux-toolkit.js.org/api/createAsyncThunk) for making API calls.
- Fetch book list from Bookstore API on Books page load.
    - Add an Action Creator, that returns a function.
    - Fetch list of books.
    - Dispatch another action (add an action type) that will pass API response to reducer and updates the state.
- Refactor your *add book* and *remove book* features to persist your changes in the server.
  - Change your existing Action Creators, so they return functions. 
  - Make changes by using API.
  - Dispatch an action (action type that existed before refactor) that will updates the state accordingly.
- *Add book* and *remove book* should work in the same way after the refactor.
- No styling is required.

### CODE REVIEW

**Review by peterrobert — CHANGES_REQUESTED** [review]
Hi @jellywiz, 

Very nice project. I love the way you have separated your code into modules and assigned specific tasks to specific modules 👏🏿 . However, there are a few changes to be made kindly check below ⬇️

### Highlights!

[ ] Good feature branch name ✔️
[ ] Descriptive pull request ✔️

 ## Required Changes ♻️
_Check the comments under the review._

- [x] It will be great to fix the template logo of your readme file. It seems to be broken. Kindly remove that Microverse logo. You can either replace it with your own or remove that logo completely.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jellywiz** [comment]
Thank you very much @peterrobert for your complement i will make sure to take care of the logo

**Review by levy002 — APPROVED** [review]
## Hello @jellywiz 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jellywiz** [comment]
Thank you for your approval @levy002

**Pull request merged**
